// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/btc.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRatioReq struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatioReq) Reset()         { *m = GetRatioReq{} }
func (m *GetRatioReq) String() string { return proto.CompactTextString(m) }
func (*GetRatioReq) ProtoMessage()    {}
func (*GetRatioReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_5b3acdffeb300fbb, []int{0}
}
func (m *GetRatioReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatioReq.Unmarshal(m, b)
}
func (m *GetRatioReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatioReq.Marshal(b, m, deterministic)
}
func (dst *GetRatioReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatioReq.Merge(dst, src)
}
func (m *GetRatioReq) XXX_Size() int {
	return xxx_messageInfo_GetRatioReq.Size(m)
}
func (m *GetRatioReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatioReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatioReq proto.InternalMessageInfo

func (m *GetRatioReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetRatioResp struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=From" json:"From,omitempty"`
	TXHash               string   `protobuf:"bytes,4,opt,name=TXHash" json:"TXHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatioResp) Reset()         { *m = GetRatioResp{} }
func (m *GetRatioResp) String() string { return proto.CompactTextString(m) }
func (*GetRatioResp) ProtoMessage()    {}
func (*GetRatioResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_5b3acdffeb300fbb, []int{1}
}
func (m *GetRatioResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatioResp.Unmarshal(m, b)
}
func (m *GetRatioResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatioResp.Marshal(b, m, deterministic)
}
func (dst *GetRatioResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatioResp.Merge(dst, src)
}
func (m *GetRatioResp) XXX_Size() int {
	return xxx_messageInfo_GetRatioResp.Size(m)
}
func (m *GetRatioResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatioResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatioResp proto.InternalMessageInfo

func (m *GetRatioResp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetRatioResp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetRatioResp) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetRatioResp) GetTXHash() string {
	if m != nil {
		return m.TXHash
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRatioReq)(nil), "proto.GetRatioReq")
	proto.RegisterType((*GetRatioResp)(nil), "proto.GetRatioResp")
}

func init() { proto.RegisterFile("proto/btc.proto", fileDescriptor_btc_5b3acdffeb300fbb) }

var fileDescriptor_btc_5b3acdffeb300fbb = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2a, 0x49, 0xd6, 0x03, 0xb3, 0x84, 0x58, 0xc1, 0x94, 0x92, 0x3a, 0x17, 0xb7,
	0x7b, 0x6a, 0x49, 0x50, 0x62, 0x49, 0x66, 0x7e, 0x50, 0x6a, 0xa1, 0x90, 0x04, 0x17, 0xbb, 0x63,
	0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x94,
	0xc2, 0xc5, 0x83, 0x50, 0x58, 0x5c, 0x20, 0x24, 0xc4, 0xc5, 0x12, 0x52, 0x59, 0x90, 0x0a, 0x55,
	0x06, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0x86, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x81, 0x05, 0x21,
	0x1c, 0x90, 0x4a, 0xb7, 0xa2, 0xfc, 0x5c, 0x09, 0x66, 0x88, 0x4a, 0x10, 0x5b, 0x48, 0x8c, 0x8b,
	0x2d, 0x24, 0xc2, 0x23, 0xb1, 0x38, 0x43, 0x82, 0x05, 0x2c, 0x0a, 0xe5, 0x19, 0x39, 0x73, 0x71,
	0x39, 0x95, 0x24, 0x07, 0x97, 0x16, 0x14, 0xe4, 0x17, 0x95, 0x08, 0x99, 0x72, 0x71, 0xc0, 0xec,
	0x14, 0x12, 0x82, 0xb8, 0x5b, 0x0f, 0xc9, 0xb5, 0x52, 0xc2, 0x18, 0x62, 0xc5, 0x05, 0x4a, 0x0c,
	0x49, 0x6c, 0x60, 0x51, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x94, 0x02, 0xff, 0xf4,
	0x00, 0x00, 0x00,
}
