[common]
    logOutPath  = "./out/out.log"
    storePath   = "./out/store"

[server]
    tcpPort     = 8082
    natsPort    = 4222

[bitcoin]
    rpcHost     = "89.111.20.200:8332" # TODO: Change to localhost
    user        = "bitcoin"
    password    = "local321"
